# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(974, 828)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setBaseSize(QtCore.QSize(600, 500))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("\n"
"")
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setProperty("tabBarAutoHide", False)
        self.tabWidget.setObjectName("tabWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.label = QtWidgets.QLabel(self.home)
        self.label.setGeometry(QtCore.QRect(360, 20, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.home)
        self.label_2.setGeometry(QtCore.QRect(360, 80, 107, 16))
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.home)
        self.groupBox.setGeometry(QtCore.QRect(30, 340, 481, 321))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 30, 461, 281))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.logoView = QtWidgets.QLabel(self.home)
        self.logoView.setGeometry(QtCore.QRect(710, 20, 71, 31))
        self.logoView.setAutoFillBackground(True)
        self.logoView.setObjectName("logoView")
        self.imageView = QtWidgets.QLabel(self.home)
        self.imageView.setGeometry(QtCore.QRect(260, 120, 54, 17))
        self.imageView.setObjectName("imageView")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.home)
        self.textBrowser_3.setGeometry(QtCore.QRect(700, 190, 171, 141))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.tabWidget.addTab(self.home, "")
        self.apps = QtWidgets.QWidget()
        self.apps.setObjectName("apps")
        self.textBrowser = QtWidgets.QTextBrowser(self.apps)
        self.textBrowser.setGeometry(QtCore.QRect(320, 80, 511, 431))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setSizeIncrement(QtCore.QSize(7, 9))
        self.textBrowser.setBaseSize(QtCore.QSize(300, 500))
        self.textBrowser.setFocusPolicy(QtCore.Qt.TabFocus)
        self.textBrowser.setTabChangesFocus(False)
        self.textBrowser.setObjectName("textBrowser")
        self.appsFullscreen = QtWidgets.QPushButton(self.apps)
        self.appsFullscreen.setGeometry(QtCore.QRect(840, 480, 31, 29))
        self.appsFullscreen.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/images/expand.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.appsFullscreen.setIcon(icon)
        self.appsFullscreen.setObjectName("appsFullscreen")
        self.appsFullscreen_back = QtWidgets.QPushButton(self.apps)
        self.appsFullscreen_back.setGeometry(QtCore.QRect(850, 700, 31, 29))
        self.appsFullscreen_back.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/images/contract.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.appsFullscreen_back.setIcon(icon1)
        self.appsFullscreen_back.setObjectName("appsFullscreen_back")
        self.utilGroupBox = QtWidgets.QGroupBox(self.apps)
        self.utilGroupBox.setGeometry(QtCore.QRect(170, 300, 131, 211))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.utilGroupBox.setFont(font)
        self.utilGroupBox.setObjectName("utilGroupBox")
        self.meshPushButton = QtWidgets.QPushButton(self.utilGroupBox)
        self.meshPushButton.setGeometry(QtCore.QRect(10, 40, 80, 26))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.meshPushButton.setFont(font)
        self.meshPushButton.setAutoDefault(False)
        self.meshPushButton.setDefault(False)
        self.meshPushButton.setFlat(False)
        self.meshPushButton.setObjectName("meshPushButton")
        self.tecplotPushButton = QtWidgets.QPushButton(self.utilGroupBox)
        self.tecplotPushButton.setGeometry(QtCore.QRect(10, 90, 80, 26))
        self.tecplotPushButton.setObjectName("tecplotPushButton")
        self.installButton = QtWidgets.QPushButton(self.apps)
        self.installButton.setGeometry(QtCore.QRect(330, 470, 121, 26))
        self.installButton.setObjectName("installButton")
        self.installListView = QtWidgets.QListView(self.apps)
        self.installListView.setGeometry(QtCore.QRect(320, 80, 511, 431))
        self.installListView.setProperty("showDropIndicator", False)
        self.installListView.setObjectName("installListView")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.apps)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 961, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.verticalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.HeaderMenu = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.HeaderMenu.setFont(font)
        self.HeaderMenu.setText("")
        self.HeaderMenu.setObjectName("HeaderMenu")
        self.horizontalLayout.addWidget(self.HeaderMenu, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.appsGroupBox = QtWidgets.QGroupBox(self.apps)
        self.appsGroupBox.setGeometry(QtCore.QRect(10, 70, 151, 221))
        self.appsGroupBox.setTitle("")
        self.appsGroupBox.setObjectName("appsGroupBox")
        self.openfoamButton = QtWidgets.QPushButton(self.appsGroupBox)
        self.openfoamButton.setGeometry(QtCore.QRect(10, 10, 134, 37))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.openfoamButton.setFont(font)
        self.openfoamButton.setMouseTracking(True)
        self.openfoamButton.setStyleSheet("")
        self.openfoamButton.setObjectName("openfoamButton")
        self.patoButton = QtWidgets.QPushButton(self.appsGroupBox)
        self.patoButton.setGeometry(QtCore.QRect(10, 60, 134, 37))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.patoButton.setFont(font)
        self.patoButton.setStyleSheet("")
        self.patoButton.setObjectName("patoButton")
        self.pumaButton = QtWidgets.QPushButton(self.appsGroupBox)
        self.pumaButton.setGeometry(QtCore.QRect(10, 110, 134, 37))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pumaButton.setFont(font)
        self.pumaButton.setStyleSheet("")
        self.pumaButton.setObjectName("pumaButton")
        self.oplrButton = QtWidgets.QPushButton(self.appsGroupBox)
        self.oplrButton.setGeometry(QtCore.QRect(10, 160, 134, 37))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oplrButton.setFont(font)
        self.oplrButton.setStyleSheet("")
        self.oplrButton.setObjectName("oplrButton")
        self.appsQframe = QtWidgets.QFrame(self.apps)
        self.appsQframe.setGeometry(QtCore.QRect(170, 80, 141, 201))
        self.appsQframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.appsQframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.appsQframe.setObjectName("appsQframe")
        self.of_runButton = QtWidgets.QPushButton(self.appsQframe)
        self.of_runButton.setGeometry(QtCore.QRect(10, 120, 80, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.of_runButton.setFont(font)
        self.of_runButton.setObjectName("of_runButton")
        self.of_testButton = QtWidgets.QPushButton(self.appsQframe)
        self.of_testButton.setGeometry(QtCore.QRect(10, 86, 80, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.of_testButton.setFont(font)
        self.of_testButton.setObjectName("of_testButton")
        self.of_installButton = QtWidgets.QPushButton(self.appsQframe)
        self.of_installButton.setGeometry(QtCore.QRect(10, 52, 80, 28))
        self.of_installButton.setMaximumSize(QtCore.QSize(85, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.of_installButton.setFont(font)
        self.of_installButton.setObjectName("of_installButton")
        self.of_documentationButton = QtWidgets.QPushButton(self.appsQframe)
        self.of_documentationButton.setGeometry(QtCore.QRect(10, 18, 113, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.of_documentationButton.sizePolicy().hasHeightForWidth())
        self.of_documentationButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.of_documentationButton.setFont(font)
        self.of_documentationButton.setStyleSheet("")
        self.of_documentationButton.setObjectName("of_documentationButton")
        self.utilGroupBox.raise_()
        self.appsFullscreen.raise_()
        self.appsFullscreen_back.raise_()
        self.textBrowser.raise_()
        self.verticalLayoutWidget.raise_()
        self.appsGroupBox.raise_()
        self.appsQframe.raise_()
        self.installListView.raise_()
        self.installButton.raise_()
        self.tabWidget.addTab(self.apps, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 974, 23))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.of_installButton.clicked.connect(self.installListView.doItemsLayout)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.label.setText(_translate("mainWindow", "DAO TMP"))
        self.label_2.setText(_translate("mainWindow", "Design Analysis..."))
        self.groupBox.setTitle(_translate("mainWindow", "News"))
        self.textBrowser_2.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans\';\">Using the Hello World guide, you’ll create a repository, start a branch, write comments, and open a pull request.</span></p></body></html>"))
        self.logoView.setText(_translate("mainWindow", "logo"))
        self.imageView.setText(_translate("mainWindow", "image"))
        self.textBrowser_3.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans\';\">Using the Hello World guide, you’ll create a repository, start a branch, write comments, and open a pull request.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.home), _translate("mainWindow", "Home"))
        self.utilGroupBox.setTitle(_translate("mainWindow", "Utilities"))
        self.meshPushButton.setText(_translate("mainWindow", "MESH"))
        self.tecplotPushButton.setText(_translate("mainWindow", "TECPLOT"))
        self.installButton.setText(_translate("mainWindow", "Start Installation"))
        self.openfoamButton.setText(_translate("mainWindow", "OpenFOAM"))
        self.patoButton.setText(_translate("mainWindow", "PATO"))
        self.pumaButton.setText(_translate("mainWindow", "PUMA"))
        self.oplrButton.setText(_translate("mainWindow", "DPLR"))
        self.of_runButton.setText(_translate("mainWindow", "Run"))
        self.of_testButton.setText(_translate("mainWindow", "Test"))
        self.of_installButton.setText(_translate("mainWindow", "Install"))
        self.of_documentationButton.setText(_translate("mainWindow", "Documentation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.apps), _translate("mainWindow", "Apps"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())

