# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mgh.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(855, 664)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.label = QtWidgets.QLabel(self.home)
        self.label.setGeometry(QtCore.QRect(250, 20, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.home)
        self.label_2.setGeometry(QtCore.QRect(250, 80, 107, 16))
        self.label_2.setObjectName("label_2")
        self.logoView = QtWidgets.QGraphicsView(self.home)
        self.logoView.setGeometry(QtCore.QRect(490, 0, 181, 131))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.logoView.setFont(font)
        self.logoView.setAutoFillBackground(False)
        self.logoView.setObjectName("logoView")
        self.groupBox = QtWidgets.QGroupBox(self.home)
        self.groupBox.setGeometry(QtCore.QRect(30, 340, 481, 201))
        self.groupBox.setObjectName("groupBox")
        self.tabWidget.addTab(self.home, "")
        self.apps = QtWidgets.QWidget()
        self.apps.setObjectName("apps")
        self.patoButton = QtWidgets.QPushButton(self.apps)
        self.patoButton.setGeometry(QtCore.QRect(10, 100, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.patoButton.setFont(font)
        self.patoButton.setObjectName("patoButton")
        self.pumaButton = QtWidgets.QPushButton(self.apps)
        self.pumaButton.setGeometry(QtCore.QRect(10, 150, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pumaButton.setFont(font)
        self.pumaButton.setObjectName("pumaButton")
        self.oplrButton = QtWidgets.QPushButton(self.apps)
        self.oplrButton.setGeometry(QtCore.QRect(10, 200, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oplrButton.setFont(font)
        self.oplrButton.setObjectName("oplrButton")
        self.label_6 = QtWidgets.QLabel(self.apps)
        self.label_6.setGeometry(QtCore.QRect(580, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.HeaderMenu = QtWidgets.QLabel(self.apps)
        self.HeaderMenu.setGeometry(QtCore.QRect(320, 0, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.HeaderMenu.setFont(font)
        self.HeaderMenu.setText("")
        self.HeaderMenu.setObjectName("HeaderMenu")
        self.openfoamButton = QtWidgets.QPushButton(self.apps)
        self.openfoamButton.setGeometry(QtCore.QRect(10, 50, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.openfoamButton.setFont(font)
        self.openfoamButton.setObjectName("openfoamButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.apps)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(240, 0, 321, 381))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.formLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.apps)
        self.label_3.setGeometry(QtCore.QRect(600, 50, 51, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.apps)
        self.label_4.setGeometry(QtCore.QRect(590, 70, 54, 17))
        self.label_4.setObjectName("label_4")
        self.tabWidget.addTab(self.apps, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 855, 23))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.label.setText(_translate("mainWindow", "DAO TMP"))
        self.label_2.setText(_translate("mainWindow", "Design Analysis..."))
        self.groupBox.setTitle(_translate("mainWindow", "News"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.home), _translate("mainWindow", "Home"))
        self.patoButton.setText(_translate("mainWindow", "PATO"))
        self.pumaButton.setText(_translate("mainWindow", "PUMA"))
        self.oplrButton.setText(_translate("mainWindow", "OPLR"))
        self.label_6.setText(_translate("mainWindow", "Utilities"))
        self.openfoamButton.setText(_translate("mainWindow", "OpenFOAM"))
        self.label_3.setText(_translate("mainWindow", "MESH"))
        self.label_4.setText(_translate("mainWindow", "TECPLOT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.apps), _translate("mainWindow", "Apps"))

