# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mgh.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(747, 518)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 681, 431))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(250, 20, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(250, 80, 107, 16))
        self.label_2.setObjectName("label_2")
        self.logoView = QtWidgets.QGraphicsView(self.tab)
        self.logoView.setGeometry(QtCore.QRect(490, 0, 181, 131))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.logoView.setFont(font)
        self.logoView.setAutoFillBackground(False)
        self.logoView.setObjectName("logoView")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.patoButton = QtWidgets.QPushButton(self.tab_2)
        self.patoButton.setGeometry(QtCore.QRect(10, 100, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.patoButton.setFont(font)
        self.patoButton.setObjectName("patoButton")
        self.pumaButton = QtWidgets.QPushButton(self.tab_2)
        self.pumaButton.setGeometry(QtCore.QRect(10, 150, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pumaButton.setFont(font)
        self.pumaButton.setObjectName("pumaButton")
        self.oplrButton = QtWidgets.QPushButton(self.tab_2)
        self.oplrButton.setGeometry(QtCore.QRect(10, 200, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oplrButton.setFont(font)
        self.oplrButton.setObjectName("oplrButton")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(580, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.HeaderMenu = QtWidgets.QLabel(self.tab_2)
        self.HeaderMenu.setGeometry(QtCore.QRect(320, 0, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.HeaderMenu.setFont(font)
        self.HeaderMenu.setText("")
        self.HeaderMenu.setObjectName("HeaderMenu")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser.setGeometry(QtCore.QRect(300, 50, 256, 261))
        self.textBrowser.setObjectName("textBrowser")
        self.columnView = QtWidgets.QColumnView(self.tab_2)
        self.columnView.setGeometry(QtCore.QRect(170, 50, 111, 291))
        self.columnView.setObjectName("columnView")
        self.documentorButton = QtWidgets.QPushButton(self.tab_2)
        self.documentorButton.setGeometry(QtCore.QRect(180, 100, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.documentorButton.setFont(font)
        self.documentorButton.setObjectName("documentorButton")
        self.installButton = QtWidgets.QPushButton(self.tab_2)
        self.installButton.setGeometry(QtCore.QRect(180, 140, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.installButton.setFont(font)
        self.installButton.setObjectName("installButton")
        self.runButton = QtWidgets.QPushButton(self.tab_2)
        self.runButton.setGeometry(QtCore.QRect(180, 220, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.runButton.setFont(font)
        self.runButton.setObjectName("runButton")
        self.testButton = QtWidgets.QPushButton(self.tab_2)
        self.testButton.setGeometry(QtCore.QRect(180, 180, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.testButton.setFont(font)
        self.testButton.setObjectName("testButton")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(570, 50, 91, 61))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 747, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", " "))
        self.label.setText(_translate("MainWindow", "DAO TMP"))
        self.label_2.setText(_translate("MainWindow", "Design Analysis..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Home"))
        self.label_3.setText(_translate("MainWindow", "Open Foam"))
        self.patoButton.setText(_translate("MainWindow", "PATO"))
        self.pumaButton.setText(_translate("MainWindow", "PUMA"))
        self.oplrButton.setText(_translate("MainWindow", "OPLR"))
        self.label_5.setText(_translate("MainWindow", "Apps"))
        self.label_6.setText(_translate("MainWindow", "Utilities"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.documentorButton.setText(_translate("MainWindow", "Documentor"))
        self.installButton.setText(_translate("MainWindow", "Install"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.testButton.setText(_translate("MainWindow", "Test"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13pt; font-weight:600;\">MESH <br />TECPLOT</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Apps"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

