# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mgh.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(821, 634)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.label = QtWidgets.QLabel(self.home)
        self.label.setGeometry(QtCore.QRect(250, 20, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.home)
        self.label_2.setGeometry(QtCore.QRect(250, 80, 107, 16))
        self.label_2.setObjectName("label_2")
        self.logoView = QtWidgets.QGraphicsView(self.home)
        self.logoView.setGeometry(QtCore.QRect(490, 0, 181, 131))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.logoView.setFont(font)
        self.logoView.setAutoFillBackground(False)
        self.logoView.setObjectName("logoView")
        self.tabWidget.addTab(self.home, "")
        self.apps = QtWidgets.QWidget()
        self.apps.setObjectName("apps")
        self.patoButton = QtWidgets.QPushButton(self.apps)
        self.patoButton.setGeometry(QtCore.QRect(10, 100, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.patoButton.setFont(font)
        self.patoButton.setObjectName("patoButton")
        self.pumaButton = QtWidgets.QPushButton(self.apps)
        self.pumaButton.setGeometry(QtCore.QRect(10, 150, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pumaButton.setFont(font)
        self.pumaButton.setObjectName("pumaButton")
        self.oplrButton = QtWidgets.QPushButton(self.apps)
        self.oplrButton.setGeometry(QtCore.QRect(10, 200, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.oplrButton.setFont(font)
        self.oplrButton.setObjectName("oplrButton")
        self.label_6 = QtWidgets.QLabel(self.apps)
        self.label_6.setGeometry(QtCore.QRect(580, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.HeaderMenu = QtWidgets.QLabel(self.apps)
        self.HeaderMenu.setGeometry(QtCore.QRect(320, 0, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.HeaderMenu.setFont(font)
        self.HeaderMenu.setText("")
        self.HeaderMenu.setObjectName("HeaderMenu")
        self.textBrowser = QtWidgets.QTextBrowser(self.apps)
        self.textBrowser.setGeometry(QtCore.QRect(300, 50, 256, 261))
        self.textBrowser.setObjectName("textBrowser")
        self.columnView = QtWidgets.QColumnView(self.apps)
        self.columnView.setGeometry(QtCore.QRect(170, 50, 256, 192))
        self.columnView.setObjectName("columnView")
        self.documentationButton = QtWidgets.QPushButton(self.apps)
        self.documentationButton.setGeometry(QtCore.QRect(180, 100, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.documentationButton.sizePolicy().hasHeightForWidth())
        self.documentationButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.documentationButton.setFont(font)
        self.documentationButton.setObjectName("documentationButton")
        self.installButton = QtWidgets.QPushButton(self.apps)
        self.installButton.setGeometry(QtCore.QRect(180, 140, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.installButton.setFont(font)
        self.installButton.setObjectName("installButton")
        self.runButton = QtWidgets.QPushButton(self.apps)
        self.runButton.setGeometry(QtCore.QRect(180, 220, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.runButton.setFont(font)
        self.runButton.setObjectName("runButton")
        self.testButton = QtWidgets.QPushButton(self.apps)
        self.testButton.setGeometry(QtCore.QRect(180, 180, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.testButton.setFont(font)
        self.testButton.setObjectName("testButton")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.apps)
        self.textBrowser_2.setGeometry(QtCore.QRect(570, 50, 91, 61))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.openfoamButton = QtWidgets.QPushButton(self.apps)
        self.openfoamButton.setGeometry(QtCore.QRect(10, 50, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.openfoamButton.setFont(font)
        self.openfoamButton.setObjectName("openfoamButton")
        self.columnView.raise_()
        self.patoButton.raise_()
        self.pumaButton.raise_()
        self.oplrButton.raise_()
        self.label_6.raise_()
        self.HeaderMenu.raise_()
        self.textBrowser.raise_()
        self.documentationButton.raise_()
        self.installButton.raise_()
        self.runButton.raise_()
        self.testButton.raise_()
        self.textBrowser_2.raise_()
        self.openfoamButton.raise_()
        self.tabWidget.addTab(self.apps, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 23))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.label.setText(_translate("mainWindow", "DAO TMP"))
        self.label_2.setText(_translate("mainWindow", "Design Analysis..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.home), _translate("mainWindow", "Home"))
        self.patoButton.setText(_translate("mainWindow", "PATO"))
        self.pumaButton.setText(_translate("mainWindow", "PUMA"))
        self.oplrButton.setText(_translate("mainWindow", "OPLR"))
        self.label_6.setText(_translate("mainWindow", "Utilities"))
        self.textBrowser.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.documentationButton.setText(_translate("mainWindow", "Documentation"))
        self.installButton.setText(_translate("mainWindow", "Install"))
        self.runButton.setText(_translate("mainWindow", "Run"))
        self.testButton.setText(_translate("mainWindow", "Test"))
        self.textBrowser_2.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13pt; font-weight:600;\">MESH <br />TECPLOT</span></p></body></html>"))
        self.openfoamButton.setText(_translate("mainWindow", "OpenFOAM"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.apps), _translate("mainWindow", "Apps"))

